#!/usr/bin/env bash
#
# setup: Script to set the PYTHONPATH and install dependencies
# Author: Mathias Roesler
# Last modified: 06/23


# Export the path to code folder in bashrc
CURRENT_DIR=$(pwd)/code
echo export PYTHONPATH=${CURRENT_DIR}:${PYTHONPATH} >> ~/.bashrc
source ~/.bashrc

# Install the required packages
pip install -r requirements.txt
