# Top level parameters
prefix="AWA025_PTA_1"
extension="png"

# Dataset image parameters
nb_pixel_x=1889
nb_pixel_y=1964
resolution=10.0

# Downsampling parameters
start_nb=518
end_nb=3208

nb_used_slices=5 # Number of slices for finding centre vectors

# Region of interest
xlim = [560, 1280] 
ylim = [1, 1964]

# Animal weight for normalisation
weight=303 # in grams

# Structure tensor parameters
[ST]
[ST.diffusion]
	erosion_threshold=10
	erosion_radius=2
	diffusion_distance=2
	
[ST.structure_tensor]
	derivative_template_width=3
	smoothing_template_width=3
	
[ST.streamlines]
	level=4
	DJ=6
	DI=6
	DK=6

[ST.ortho]
  level=2
