# Top level parameters
prefix="AWA026_PTA_1"
extension="png"

# Dataset image parameters
nb_pixel_x=1844
nb_pixel_y=1961
resolution=10.0

# Downsampling parameters
start_nb=588
end_nb=2938

nb_used_slices=5 # Number of slices for finding centre vectors

# Region of interest
xlim = [1, 1844] 
ylim = [1, 1961]

# Animal weight for normalisation
weight=254 # in grams

# Structure tensor parameters
[ST]
[ST.diffusion]
	erosion_threshold=10
	erosion_radius=2
	diffusion_distance=2
	
[ST.structure_tensor]
	derivative_template_width=3
	smoothing_template_width=3
	
[ST.streamlines]
	level=4
	DJ=6
	DI=6
	DK=6

[ST.ortho]
  level=2
