# Top level parameters
prefix="AWA015_PTA_2_Ova"
extension="png"

# Dataset image parameters
nb_pixel_x=2071
nb_pixel_y=3012
resolution=6.008106

# Downsampling parameters
start_nb=1000
end_nb=2300


nb_used_slices=5 # Number of slices for finding centre vectors

# Region of interest
xlim = [1, 2071] 
ylim = [1, 3012]

# Structure tensor parameters
[ST]
[ST.diffusion]
	erosion_threshold=10
	erosion_radius=4
	diffusion_distance=2
	
[ST.structure_tensor]
	derivative_template_width=5
	smoothing_template_width=5
	
[ST.streamlines]
	level=5
	DJ=12
	DI=12
	DK=12

