# Top level parameters
prefix="AWB012_PTA_1"
extension="png"

# Dataset image parameters
nb_pixel_x=2452
nb_pixel_y=2452
resolution=10.000018

# Downsampling parameters
start_nb=140
end_nb=3025

nb_used_slices=5 # Number of slices for finding centre vectors

# Region of interest
xlim = [1, 2452] 
ylim = [1, 2452]

# Animal weight for normalisation
weight=294 # in grams

# Structure tensor parameters
[ST]
[ST.diffusion]
	erosion_threshold=10
	erosion_radius=2
	diffusion_distance=2
	
[ST.structure_tensor]
	derivative_template_width=3
	smoothing_template_width=3
	
[ST.streamlines]
	level=4
	DJ=6
	DI=6
	DK=6

[ST.ortho]
  level=2
