# Top level parameters
prefix="TestImage001"
extension="png"

# Dataset image parameters
nb_pixel_x=701
nb_pixel_y=701
resolution=10.943253

# Downsampling parameters
start_nb=310
end_nb=2130

nb_used_slices=5 # Number of slices for finding centre vectors

# Region of interest
xlim = [632, 1500] 
ylim = [700, 3152]

# Structure tensor parameters
[ST]
[ST.diffusion]
	erosion_threshold=10
	erosion_radius=2
	diffusion_distance=2
	
[ST.structure_tensor]
	derivative_template_width=3
	smoothing_template_width=3
	
[ST.streamlines]
	level=4
	DJ=6
	DI=6
	DK=6

